### ISSUE TITLE
when going with a same hero on location where you have crashed save, your current save duplicates and crashes, and you can't play any of them

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#26] opened 2020-08-07 19:58 UTC
error log
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: xiaomi
Device: daisy_sprout
Model: Mi A2 Lite
Manufacturer: Xiaomi
Product: daisy
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.8a-INDEV
Installed On: 2020-07-31 17:44:13
Updated On: 2020-07-31 17:44:13
Current Date: 2020-08-07 22:55:38

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from null array
	at com.shatteredpixel.yasd.general.actors.buffs.Preparation.act(Preparation.java:124)
	at com.shatteredpixel.yasd.general.actors.Actor.process(Actor.java:271)
	at com.shatteredpixel.yasd.general.scenes.GameScene$2.run(GameScene.java:582)

***** END OF LOG *****

**Comment by Smujb** [comment] 2020-08-07 20:01
I'm not sure I quite understand... Are you saying that the crashed save's maps got into your new game, and when it crashed you get two staves that crash? This would be because the old save revives in some way I think. Since it's caused by a corrupted save it could be hard to fix but I'll try.

**Comment by Xazmadan** [comment] 2020-08-07 20:03
update:sometimes you see the sewers level on a 2-6 frames, but the stage is non-sewer, all level are revealed from war fog

**Comment by Smujb** [comment] 2020-08-07 20:05
Yup, known issue. Delete the saves and restart. Corrupted saves aren't delete and elements of them may appear in the next run. It's a bug caused by another bug so it's to be expected, but I'll leave this open and try to fix.

**Comment by Xazmadan** [comment] 2020-08-07 20:05
> I'm not sure I quite understand... Are you saying that the crashed save's maps got into your new game, and when it crashed you get two staves that crash? This would be because the old save revives in some way I think. Since it's caused by a corrupted save it could be hard to fix but I'll try.

looks like old crashed save break all location generation until deleted

**Comment by Smujb** [comment] 2020-08-07 20:06
Yep. It loads the old levels because the save wasn't entirely deleted.

**Comment by Smujb** [comment] 2020-08-15 12:45
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/b1e681b335c0323cb7488c0dd56cdae50eec621b

**Closed by Smujb** 2020-08-15 12:45 UTC
