### ISSUE TITLE
Issues as of 0.4.6

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#21] opened 2020-07-19 12:49 UTC
commit 87c4ac9bbb0e99bea3982c90921d4859f57ba109

* No difficulty setting offered when starting a game;
* No degradation mechanic present (including when loading a savefile from previous version where it is present). But the stone is still stone of repair instead of aggression;
* Scroll of transmutation bears wrong icon (green uparrow, same as SoU);
* Diving out sometimes results in being near the deep water, not directly on top of it. Also diving out resulted in being inside a wall, unable to move except of by teleport;
* (present also in earlier versions) Text for moving between levels (including diving in/out) is often wrong. For example, at the very beginning of the same it says "Returning to the depth 1". Then going underwayer it also says "returning".
* At least two invisible slots in the main inventory.
* Are there supposed to be rooms inaccesible without diving? Is diving supposed to be a workaround for locked or barricated doors?
* Is water elecrified by shoking trap supposed to be normal if dived under?

**Comment by vi** [comment] 2020-07-19 12:57
> Your chilling sword is about to degrade

So maybe it's only that red/green line is missing in UI, not the mechanic?

**Comment by Smujb** [comment] 2020-07-19 13:38
All known, issues with the port except:
- At least two invisible slots in the main inventory.
This was an issue with 0.8.1 Shattered actually so I probably forgot to port a commit that fixed it.
- Scroll of transmutation bears wrong icon (green uparrow, same as SoU);
Noted.
- Diving out sometimes results in being near the deep water, not directly on top of it. Also diving out resulted in being inside a wall, unable to move except of by teleport;
Damn it. I thought I had fixed that. This issue makes no sense at all.
- 
Are there supposed to be rooms inaccesible without diving? Is diving supposed to be a workaround for locked or barricated doors?
Certain level types may spawn rooms that have nothing in them and can't be accessed if they have the "town" feeling. This is because they would have been empty space otherwise.
- Is water elecrified by shoking trap supposed to be normal if dived under?
Not really, but due to being a different level, writing interactions between surface and underneath is hard.

**Comment by Smujb** [comment] 2020-07-19 13:47
As for the resurfacing in the wrong place issue, I have not been able to reproduce it.

**Comment by Smujb** [comment] 2020-07-19 13:49
Was this issue either found in an earlier release or an old save? If not I'll need to do more extensive testing.

**Comment by Smujb** [comment] 2020-07-19 14:42
Update: reproduced it. Seems rarer than in previous versions, but still happens. Some levels are completely fine and others are broken. Going to try to fix ASAP.

**Comment by vi** [comment] 2020-07-19 15:19
Screenshots:

Wrong marker for the scroll:

![1](https://user-images.githubusercontent.com/173219/87878324-33fe7380-c9ec-11ea-815f-804cc0de498d.png)

Bad UI for buying item. May be the same cause as invisible degradation bar.

![2](https://user-images.githubusercontent.com/173219/87878339-4c6e8e00-c9ec-11ea-95f3-2551526ebfc9.png)

Note that Power Saver is active, but the issue is the same even without power saver and in landscape mode.

**Comment by vi** [comment] 2020-07-19 17:17
As of cc0e775ae9d149b7d357a009307df54d2266d2d3, at least some UI issues are fixed.

There is another minor one: bronze lock looks sheared:

![3](https://user-images.githubusercontent.com/173219/87880747-d7f01b00-c9fc-11ea-9bae-d3a3a9ca0600.png)

**Comment by vi** [comment] 2020-07-19 18:00
Also drunkedness icon does not fade away in a way that was introduced in the recent Shattered update.

**Comment by Smujb** [comment] 2020-07-19 18:01
Icon fading was directly ported - it exists on a buff by buff basis. I added it to Wet but forgot Drunk. Will add

**Comment by vi** [comment] 2020-07-19 18:34
(Now realized that there are both "wet" debuff and diving, but they are somehow not connected).

**Comment by Smujb** [comment] 2020-08-15 12:52
Seeing as most of these issues were fixed a while ago, I'm going to create a new issue with the title `Text for moving between levels (including diving in/out) is often wrong.` (the only remaining one) and close this.

**Closed by Smujb** 2020-08-15 12:52 UTC

**Comment by vi** [comment] 2020-08-15 15:10
In future, shall I create series of individual issues (which may have considerable duplicated text) or keep using itemized issues?

**Comment by Smujb** [comment] 2020-08-15 15:11
It doesn't really matter; the main thing is that 90% of this issue is no longer relevant so keeping it up makes little sense.
